Flammel:
  Fission:
    templateDirectories:
      - Sites/Flammel.FissionDemoVm/Resources/Private/Fission
    presenters:
      'Flammel.FissionDemoVm:Layout.Navbar': 'Flammel\FissionDemoVm\Fission\Presenter\NavbarPresenter'
      'Flammel.FissionDemoVm:Content.Image': 'Flammel\FissionDemoVm\Fission\Presenter\ImagePresenter'
